a.out : main.o coder.o command.o
	gcc main.o coder.o command.o -o a.out

main.o : main.c
	gcc -c main.c -o main.o

coder.o : coder.c
	gcc -c coder.c -o coder.o

command.o : command.c
	gcc -c command.c -o command.o
